version: '2'
services:
  web:
    image: node
    build: .
    ports:
     - "3000:3080"
    volumes:
     - .:/
    depends_on:
     - mongo
  mongo:
    image: mongo
  #  ports:
  #  - "27017:27017"